[[tagging]]
== Memory tagging extension (Zimte)

The Zimte extension divides address space of the program in equal memory chunks
of 16 bytes (hereafter `mc`). Each `mc` in address space can be associated with
a tag (hereafter `mc_tag`) by software and `mc_tag` for `mc` is stored in
memory defined by extension Svatag (see <<virtualtag>>).

Software (runtime memory allocator or compiler) that constructs pointers to
access memory (and thus memory chunks) is expected to place a tag (hereafter
`pointer_tag`) in high unused bits of the pointer as defined by the pointer
masking extensions cite:[PMASKING]. Thus `Zimte` depends on the pointer masking
extension and is applicable to only for XLEN=64. Pointer masking has to be
enabled as a requirement for memory tagging to be enabled in the execution
environment.

To maintain binary compatibility with implementations where memory tagging
extension may not be implemented or may not be enabled for a workload,
instruction encodings for memory tagging are taken from zimop cite:[ZIMOP]
encoding and thus make memory tagging extension dependent on zimop.

=== Tag widths

Width of the `pointer_tag` (hereafter `pointer_tag_width`) can be 4 bit or 7
bit wide depending on implementation. Discovery of `pointer_tag_width` is
described in <<MEMTAG_CSR_CTRL>> section. Width of the `mc_tag` (hereafter
`mc_tag_width`) is dependent on the `pointer_tag_width`. Following table
describes valid configurations of `pointer_tag_width` and `mc_tag_width`.

.`pointer_tag` and `mc_tag` valid configurations
[width=100%]
[%header, cols="^4,^4"]
|===
|`pointer_tag_width`| `mc_tag_width`
|  4                | 4
|  7                | 8
|===

=== Tag placement in pointer

Zimte defines following instructions to annotate a pointer with `pointer_tag`
and perform arithmetics on `pointer_tag` in a tagged pointer. Placement and
arithmetics on `pointer_tag` are performed in-place in masked bits (as defined
by pointer masking extension) starting at b63. Instructions introduced to
place and perform arithmetics on `pointer_tag` are encoded using `MOP.RR.1`
from zimop extension.

[NOTE]
====
Existing RISC-V instructions can also be used to place (and do arithmetics)
`pointer_tag` in masked bits of a pointer. But doing so increases code size,
more so if tagging for stack memory is enabled. And new instructions help
contain the code size growth.
====

Following are the instructions to place `pointer_tag` in the source register

==== Generate a tag - gentag rd, rs1

If memory tagging is enabled in the current execution environment (see
<<MEM_TAG_EN>>), hart clears `rd`, generates a `pointer_tag` value with at
least 1-bit different from `rs1[XLEN:XLEN-pointer_tag_width+1]` and places the result
back in `rd[XLEN:XLEN-pointer_tag_width+1]`.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['pointer_tag']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['tagged_pointer']},
  {bits:  4, name: 'tag_imm4', attr:['0000']},
  {bits:  1, name: '0', attr:['0']},
  {bits:  7, name: '1000011', attr:['gentag']},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
=====
See Appendix for example how this can be used by codegen.
=====

==== Arithmetics on pointer tag - addtag rd, rs1, #tag_imm4

`addtag rd, rs1` is a pseudo for `gentag rd, rs1` with tag_imm4 != 0. If memory
tagging is enabled in the current execution environment (see <<MEM_TAG_EN>>),
`addtag rd, rs1` instruction performs addition of `pointer_tag` specified in
`rs1[XLEN:XLEN-pointer_tag_width+1]` with the unsigned value `tag_imm4` shifted
left by `XLEN - pointer_tag_width` bits and places incremented `pointer_tag`
value in `rd[XLEN:XLEN-pointer_tag_width+1]`.
If memory tagging is disabled in the current execution environment,
then `addtag` instruction falls back to zimop behavior
and zeroes destination register.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['pointer_tag']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['tagged_pointer']},
  {bits:  4, name: 'tag_imm4', attr:['non-zero']},
  {bits:  1, name: '0', attr:['0']},
  {bits:  7, name: '1000011', attr:['addtag']},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
=====
addtag instruction can be used by the compiler for generating distinct pointer
tags derived from a base tag (base tag obtained via gentag). Compiler can use
this mechanism to assign different tags (with same base tag) for consecutive
objects on stack and mitigate adjacent overflow bugs. This also helps with
language runtime during events like exception unwind to calculate tags for
objects on stack in a deterministic manner.

See Appendix for example how this can be used by codegen.
=====

[[TAG_STORE]]
=== set tag(s) for memory chunk(s)

Zimte defines an instruction to store tag (i.e. `pointer_tag`) value(s) for
consecutive 1 to 16 memory chunk(s). Base address of the first memory chunk is
calculated by doing `rs1 & (~0xF)`. Count of memory chunk is encoded as 4 bit
immediate (#chunk_count) in the instruction. This instruction is encoded using
`MOP.RR.0` from zimop extension. Immediate encodings in #chunk_count are zero
based and thus #chunk_count = 0 means first chunk and #chunk_count = 15 means
16th chunk.

[NOTE]
====
Load tag operation is omitted from extension definition because its not
needed. Situations where load tag is required deemed to be not performance
critical paths. Furthermore, if software desires to read tag in these non-
performance critical paths, it can do so by creating an alternate read-only
mapping of tag storage with the help of supervisor software.

Since extension is still in development phase, if load tag operation is
required by software, it can be added.
====

==== Store tag(s) for memory chunk(s): settag rs1, #chunk_count

If memory tagging is enabled in the current execution environment (see
<<MEM_TAG_EN>>), `settag` instruction creates a `mc_tag` =
`rs1[XLEN:XLEN-pointer_tag_width+1]` and stores `mc_tag(s)` for consecutive
memory chunks encoded by `chunk_count` starting with the first memory chunk
calculated from virtual address specified in `rs1`.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['00000']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['tagged_pointer']},
  {bits:  4, name: 'imm4', attr:['chunk_count']},
  {bits:  1, name: '0', attr:['0']},
  {bits:  7, name: '1000001', attr:['settag']},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
====
.Note on tag stores
When `pointer_tag_width = 4 bit`, `mc_tag` (stored) width is 4 bit and thus
maximum width of tag store operation can be 64 bit wide (each memory chunk
needs 4 bit tag and maximum possible chunks are 16. 4x16 = 64 bit). When
`pointer_tag_width = 7 bit`, `mc_tag` (stored) width is 8 bit and thus maximum
width of tag store operation can be 128 bit wide (each memory chunk needs 8 bit
and maximum possible chunks are 16. 8x16 = 128 bit).
====

`settag` may end being a read, modify and then write operation on the
memory region defined by Svatag extension and there are no atomicity
requirements on the implementation. If atomicity is desired then it is
software's responsibility.

`settag` can generate store operations larger than maximum store width
supported by implementation and implementation may choose to split it
into multiple stores with no ordering requirements or dependencies among
splitted stores.

* Memory ordering requirement

  A memory access (load or store) to some virtual address `va` can not bypass
  the older store initiated by `settag rs1=va`.

  This specification defines tag as the entity associated to virtual addresses.
  In case of aliasing (multiple virtual addresses map to same physical address),
  it is software's responsibility to ensure that the tags are set according to
  software's need for respective virtual address prior to memory accesses via
  aliased virtual address.

* Exceptions

  `settag` can raise store page fault or access fault depending on how tag
  storage is oragnized. If implementation doesn't support misaligned accesses,
  `settag` instruction can raise misaligned exception if calculated address
  for locating tag is unaligned. Tag storage memory must be idempotent memory
  else `settag` raise store/AMO access-fault exception.

[[TAG_CHECKS]]
=== tag checks and privilege modes

==== M-mode
If memory tagging is enabled in M-mode (see <<MEM_TAG_EN>>), all regular loads
and stores are subject to memory tagging checks.

==== Less than M-mode
If memory tagging is enabled in the current execution environment (see
<<MEM_TAG_EN>>) and `satp.MODE == Bare`, then all loads and stores are subject
to tag checks.

If memory tagging is enabled in the current execution environment and
`satp.MODE != Bare`, then only loads/stores belonging to pages marked as tagged
page (see <<TAGGED_PAGE>>) in the first stage page table are subject to memory
tagging checks.

==== tag checks
Once a load/store is determined to be subject to memory tagging checks,
following checks are performed

* If `pointer_tag == 0` in pointer and per-pointer tag check elision is enabled
  (see <<TAGCHECK_ELIDE>>), then tag checks are completely elided on that memory
  access.

* Hart evaluates expression `mc_tag == pointer_tag` and if false then hart
  raises a software check exception with tval = 4.

If a load / store is subject to tag checks, fetching `mc_tag` from the tag
memory region holding tags may also result in a load page fault or load access
fault and thus the hart report the virtual address of the tag in `xtval`.

[[ASYNC_SW_CHECK]]
=== Asynchronous reporting for tag mismatches

To improve performance, software check exceptions due to tag mismatches on
stores can be reported asynchronously. This means that reported `epc` might not
be the reason for tag mismatch and software must do additional analysis to
infer which store resulted in software check exception. This behavior is can
be optionally turned on through `__x__envcfg` CSR for next less privilege mode
(see <<MEMTAG_CSR_CTRL>>).

Note that tag check violations on loads must always be reported synchronously.

[[TAGGED_PAGE]]
=== Tag checks on page basis

Memory tagging extension extends first stage page table by introducing a new
leaf PTE bit (bit position TBD) termed as `MTAG`. If an implementation
implements memory tagging extension then `PTE.MTAG` is no more a reserved bit,
irrespective of memory tagging is enabled or not for current execution
environment.

If memory tagging is enabled for the current execution environment (see
<<MEM_TAG_EN>>) and PTE.MTAG = 1, then the page is considered a tagged page and
load / stores to such a page are subject to tag checks (see <<TAG_CHECKS>>).
Underlying tagged page must be idempotent memory else tag look up for referenced
virtual memory will result in load access-fault exception.

[NOTE]
====
A bit in page table entry allows software to enable memory tagging on per-page
basis and thus can have several discontigous regions on which tagging can be
enabled. Depending on complexity of program and memory allocator(s), software
can choose to enable on per-page basis. Furthermore, this allows software to
enable memory tagging only for heap.
====

[[TAGCHECK_ELIDE]]
=== Per-pointer tag check elision

Certain pointers can be elided for tag checks if software (compiler) can
statically determine that they are safe to access. One such situation is
function locals where compiler can statically determine that memory access is
not out of bounds or out of scope. Although pointers to function locals passed
to another function will require tag checks. Thus page tables will mark such
pages tagged page. Thus `Zimte` defines a `EN_TAG_ELIDE`(see
<<MEMTAG_CSR_CTRL>>) control in `__x__envcfg` CSR. If `EN_TAG_ELIDE` is set
then a pointer with `pointer_tag == 0` is not subject to tag checks. If
`EN_TAG_ELIDE` control is clear in `__x__envcfg` CSR and page is tagged page
then memory access is subject to tag check irrespective of `pointer_tag` value
in pointer.

[NOTE]
=====
Compiler can elide tag checks on memory accesses local to a function and thus
gain performance back. If pointer to a local stack variable is passed to
another function, then compiler can set a tag for that local variable and
annotate pointer with `pointer_tag`. Something along the below listing.

[listing]
-----
    function_prologue:
        addi sp, sp, -512 # stack frame size of 512 bytes
        gentag t0, sp     # generate a pointer_tag and place it in t0
         :
        xor sp, sp, t0
        addi a1, sp, 16
        addtag t0, sp, 1  # tag_imm4 = 1
        addi a1, a1, t0   # annotate pointer `a1` with tag
        settag a1         # set tag in tag storage
        addi a2, sp, 32
        addtag t0, sp, 2  # tag_imm4 = 2
        addi a2, a2, t0   # annotate pointer `a2` with tag
        settag a1         # set tag in tag storage
        jal foo           # call function `foo` with tagged pointers `a1` and `a2`
-----

=====

[[MEMTAG_CSR_CTRL]]
=== CSR bits for memory tagging

In M-mode, enable for memory tagging is controlled via `mseccfg` CSR.

Enablement for privilege modes less than M-mode is controlled through
`__x__envcfg` CSR. Zimte adds two bits termed as `MTE_MODE` to `__x__envcfg`
CSR which controls enabling of memory tagging and `pointer_tag_width` for the
next privilege mode. A `MT_ASYNC` bit is added to `__x__envcfg` CSR and if set,
software check exceptions due to tag mismatches on store operations can be
reported asynchronously (see <<ASYNC_SW_CHECK>>). An `EN_TAG_ELIDE` bit is
added to `__x__envcfg` CSR and if set, a pointer with `pointer_tag == 0`
becomes special pointer tag and bypasses tag checks (see <<TAGCHECK_ELIDE>>).

[[MEM_TAG_EN]]
==== Memory tagging enable and pointer_tag_width

The term `xMTE_MODE` is used to determine if memory tagging is enabled in
current execution environment (privilege mode).

Following table describes different encodings of `MTE_MODE` and corresponding
configuration

.`MTE_MODE` encoding and its meaning
[width=100%]
[%header, cols="^4,^12"]
|===
|`MTE_MODE` | Memory tagging state
|  00       | Disabled
|  01       | Reserved
|  10       | Enabled, pointer_tag_width = 4
|  11       | Enabled, pointer_tag_width = 7
|===

  If memory tagging is implemented, implementation must implement
  `pointer_tag_width = 4` at minimum. To discover maximum supported
  `pointer_tag_width`, software can write `0b11` to `MTE_MODE` field in the
  `__x__envcfg` CSR and read it back. If read back value is `0b11` then
  implementation supports both `pointer_tag` widths.

  If xMTE_MODE == 0b00 then xMTE_MODE.MT_ASYNC becomes WPRI

==== Machine Security Configuration Register(`mseccfg`)

.Machine security configuration register(`mseccfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'MML'},
  {bits:  1, name: 'MMWP'},
  {bits:  1, name: 'RLB'},
  {bits:  5, name: 'WPRI'},
  {bits:  1, name: 'USEED'},
  {bits:  1, name: 'SSEED'},
  {bits:  1, name: 'MLPE'},
  {bits: 21, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MTE_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits:  1, name: 'EN_TAG_ELIDE'},
  {bits: 26, name: 'WPRI'},
], config:{lanes: 4, hspace:1024}}
....

The Zimte extension adds the `MTE_MODE` field (bit 34:2) to `mseccfg`. When the
`MTE_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
M-mode.

When `MTE_MODE` is `0b00`, the following rules apply to M-mode:
* Zimte instructions will revert to their behavior as defined by Zimop.

==== Machine Environment Configuration Register (`menvcfg`)

.Machine environment configuration register (`menvcfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 24, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MTE_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits:  1, name: 'EN_TAG_ELIDE'},
  {bits: 22, name: 'WPRI'},
  {bits:  1, name: 'CDE'},
  {bits:  1, name: 'ADUE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

The Zimte extension adds the `MTE_MODE` field (bit 34:2) to `menvcfg`. When the
`MTE_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
HS/S-mode.

When `MTE_MODE` is `0b00`, the following rules apply to HS/S-mode:

* Zimte instructions will revert to their behavior as defined by Zimop.

==== Supervisor Environment Configuration Register (`senvcfg`)

.Supervisor environment configuration register (`senvcfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 24, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MTE_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits:  1, name: 'EN_TAG_ELIDE'},
  {bits: 26, name: 'WPRI'},
], config:{lanes: 4, hspace:1024}}
....

The Zimte extension adds the `MTE_MODE` field (bit 34:2) to `senvcfg`. When the
`MTE_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
VU/U-mode.

When `MTE_MODE` is `0b00`, the following rules apply to VU/U-mode:

* Zimte instructions will revert to their behavior as defined by Zimop.

==== Hypervisor Environment Configuration Register (`henvcfg`)

.Hypervisor environment configuration register (`henvcfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 24, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MTE_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits:  1, name: 'EN_TAG_ELIDE'},
  {bits: 22, name: 'WPRI'},
  {bits:  1, name: 'CDE'},
  {bits:  1, name: 'ADUE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

The Zimte extension adds the `MTE_MODE` field (bit 34:2) to `henvcfg`. When the
`MTE_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
VS-mode.

When `MTE_MODE` is `0b00`, the following rules apply to VS-mode:

* Zimte instructions will revert to their behavior as defined by Zimop.

<<<

=== Appendix
==== Example: stack tagging codegen
[listing]
-----
    function:
        # N.B. sp remains untagged at all times
        addi sp, sp, -512 # stack frame size of 512 bytes
        gentag t0, zero   # generate a pointer_tag and place it in t0
         :
        # first object is tagged <random tag> + 1
        addi s1, sp, 16
        addtag t1, t0, 1  # tag_imm4 = 1
        or s1, s1, t1
         :
        # second object is tagged <random tag> + 2
        addi s2, sp, 32
        addtag t1, t0, 2  # tag_imm4 = 2
        or s2, s2, t1
         :
        # scope of second object starts, tag
        settag s2, 1
        # [...] do things with s2 while in scope
        # scope of second object ends, tag back to zero
        addi s2, sp, 16
        settag s2, 1
-----
