[[tagging]]
== Memory tagging extension (Zimt)

The Zimt extension divides address space of the program in equal memory chunks
of 16 bytes (hereafter `mc`). Each `mc` in address space can be associated with
a tag (hereafter `mc_tag`) by software and `mc_tag` for `mc` is stored in
memory defined by extension Svatag (see <<virtualtag>>).

Software (runtime memory allocator or compiler) that constructs pointers to
access memory (and thus memory chunks) is expected to place a tag (hereafter
`pointer_tag`) in high unused bits of the pointer as defined by the pointer
masking extensions cite:[PMASKING]. Thus `Zimt` depends on the pointer masking
extension and is applicable to only for XLEN=64. Pointer masking has to be
enabled as a requirement for memory tagging to be enabled in the execution
environment.

To maintain binary compatibility with implementations where memory tagging
extension may not be implemented or may not be enabled for a workload,
instruction encodings for memory tagging are taken from zimop cite:[ZIMOP]
encoding and thus make memory tagging extension dependent on zimop.

A memory tag (`mc_tag`) can be up to 8 bits wide. Thus, depending on memory
chunk counts, a `load tag` or `store tag` (see taxonomy for loads and stores)
may trigger a misaligned memory access exception (e.g by performing a 2-byte
tag access on an odd address boundary). An implementation can avoid penalty for
such misaligned tag accesses by implementing the Zicclsm extension.

[NOTE]
The memory tagging extension is based on the Pointer Masking extension and
follows the same rules for memory access. For further information, see section
24.2.6 of the privilege specification: Memory Accesses Subject to Pointer
Masking.

=== Taxonomy for loads and stores

`Zimt` introduces new type of loads and stores to the hart and enforces tag
checks on certain loads and stores. Following terminologies are defined for
better clarity and will be used in the rest of the specification.

==== Regular load and regular store operations
Load and store operating on a page with permissions `--R`, `X-R`, `-WR` and
`XWR` are termed as a `regular load` and `regular store`. Regular load and
regular store memory operations are generated from an instruction (except
`settag` and `checktag`) defined by ISA to perform memory accesses.

==== Checked load and store
Regular load and store which is subject to tag check is termed as checked load
and store (or checked memory access)

==== Unchecked load and store
Regular load and store which is not subject to tag check is termed as unchecked
load and store (unchecked memory access).

==== Load tag and store tag operations
`load tag` operation is a load of tag from tag storage as defined by Svatag or
Smvatag extensions. `store tag` operation is a store of tag to tag storage as
defined by Svatag or Smvatag extensions. `load tag` operation requires
permission for tag storage memory to be --R while `store tag` operation
require permission to be -WR.

Checked loads and stores shall generate load tag operation in order to fetch
the tag for the memory chunk. `settag` instruction may generate a load tag
followed by a store tag memory operation.

=== Tag widths

Width of the `pointer_tag` (hereafter `pointer_tag_width`) can be 4 bit or 7
bit wide depending on implementation. Discovery of `pointer_tag_width` is
described in <<MEMTAG_CSR_CTRL>> section. Width of the `mc_tag` (hereafter
`mc_tag_width`) is dependent on the `pointer_tag_width`. Following table
describes valid configurations of `pointer_tag_width` and `mc_tag_width`.

.`pointer_tag` and `mc_tag` valid configurations
[width=100%]
[%header, cols="^4,^4"]
|===
|`pointer_tag_width`| `mc_tag_width`
|  4                | 4
|  7                | 8
|===

=== Tag placement in pointer

Zimt defines following instructions to annotate a pointer with `pointer_tag`
and perform arithmetics on `pointer_tag` in a tagged pointer. Placement and
arithmetics on `pointer_tag` are performed in-place in masked bits (as defined
by pointer masking extension) starting at b63. Instructions introduced to
place and perform arithmetics on `pointer_tag` are encoded using `MOP.RR.1`
from zimop extension.

[NOTE]
====
Existing RISC-V instructions can also be used to place (and do arithmetics)
`pointer_tag` in masked bits of a pointer. But doing so increases code size,
more so if tagging for stack memory is enabled. And new instructions help
contain the code size growth.
====

Following are the instructions to place `pointer_tag` in the source register

==== Generate a tag - gentag rd

If memory tagging is enabled in the current execution environment (see
<<MEM_TAG_EN>>), hart clears `rd`, generates a `pointer_tag` value and places
the result in `rd[XLEN:XLEN-pointer_tag_width+1]`.

If memory tagging is disabled in the current execution environment (see
<<MEM_TAG_EN>>), then `gentag` instruction falls back to zimop behavior and zeroes
destination register.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['pointer_tag']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['00000']},
  {bits:  4, name: 'tag_imm4', attr:['0000']},
  {bits:  1, name: '0', attr:['0']},
  {bits:  7, name: '1000011', attr:['gentag']},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
=====
See Appendix for example how this can be used by codegen.
=====

==== Arithmetics on pointer tag - addtag rd, rs1, #tag_imm4

If memory tagging is enabled in the current execution environment (see
<<MEM_TAG_EN>>), `addtag rd, rs1` instruction performs addition of
`pointer_tag` specified in `rs1[XLEN:XLEN-pointer_tag_width+1]` with the
unsigned value `tag_imm4` shifted left by `XLEN - pointer_tag_width` bits and
places incremented `pointer_tag` value in `rd[XLEN:XLEN-pointer_tag_width+1]`.

If memory tagging is disabled in the current execution environment (see
<<MEM_TAG_EN>>), then `addtag` instruction falls back to zimop behavior and
zeroes destination register.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['pointer_tag']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['tagged_pointer']},
  {bits:  4, name: 'tag_imm4', attr:['non-zero']},
  {bits:  1, name: '0', attr:['0']},
  {bits:  7, name: '1000011', attr:['addtag']},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
=====
addtag instruction can be used by the compiler for generating distinct pointer
tags derived from a base tag (base tag obtained via gentag). Compiler can use
this mechanism to assign different tags (with same base tag) for consecutive
objects on stack and help catch adjacent overflow bugs. This also helps with
language runtime during events like exception unwind to calculate tags for
objects on stack in a deterministic manner.

See Appendix for example how this can be used by codegen.
=====

[[TAG_STORE]]
=== set tag(s) for memory chunk(s)

Zimt defines an instruction to store tag (i.e. `pointer_tag`) value(s) for
consecutive 1 to 16 memory chunk(s). Base address of the first memory chunk is
calculated by doing `rs1 & (~0xF)`. Count of memory chunk is encoded as 4 bit
immediate (#chunk_count) in the instruction. This instruction is encoded using
`MOP.RR.0` from zimop extension. Immediate encodings in #chunk_count are zero
based and thus #chunk_count = 0 means first chunk and #chunk_count = 15 means
16th chunk.

[NOTE]
====
REMOVEME: after development phase of spec is done.
`gettag` operation is omitted from extension definition because its not
needed. Situations where `gettag` is required deemed to be not performance
critical paths. Furthermore, if software desires to read tag in these non-
performance critical paths, it can do so by creating an alternate read-only
mapping of tag storage with the help of supervisor software.

Since extension is still in development phase, if `gettag` operation is
required by software, it can be added.
====

==== Store tag(s) for memory chunk(s): settag rs1, #chunk_count

If memory tagging is enabled in the current execution environment (see
<<MEM_TAG_EN>>), `settag` instruction creates a `mc_tag` =
`rs1[XLEN:XLEN-pointer_tag_width+1]` and generate a `store tag` memory
operation with store data = `mc_tag(s)` for consecutive memory chunks encoded
by `chunk_count` starting with the first memory chunk calculated from virtual
address specified in `rs1`.

If memory tagging is disabled in the current execution environment (see
<<MEM_TAG_EN>>), then `settag` instruction falls back to zimop behavior and
zeroes x0, which is a no-op.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['00000']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['tagged_pointer']},
  {bits:  4, name: 'imm4', attr:['chunk_count']},
  {bits:  1, name: '0', attr:['0']},
  {bits:  7, name: '1000001', attr:['settag']},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
====
.Note on tag stores
When `pointer_tag_width = 4 bit`, `mc_tag` (stored) width is 4 bit and thus
maximum width of tag store operation can be 64 bit wide (each memory chunk
needs 4 bit tag and maximum possible chunks are 16. 4x16 = 64 bit). When
`pointer_tag_width = 7 bit`, `mc_tag` (stored) width is 8 bit and thus maximum
width of tag store operation can be 128 bit wide (each memory chunk needs 8 bit
and maximum possible chunks are 16. 8x16 = 128 bit).
====

Depending on width of `mc_tag`, `settag` may end up being a read, modify and
then write operation on the memory region defined by Svatag and Smvatag
extensions. There are no atomicity requirements on the implementation for
`settag` instruction. If atomicity is desired for `store tag` operation then it
is software's responsibility using existing mechanisms.

`settag` can generate store operations larger than maximum store width
supported by implementation and implementation may choose to split it
into multiple stores which follows hart's memory consistency model. There are
no ordering requirements or dependencies among splitted stores.

===== Memory ordering requirement

A regular memory access (regular load or regular store) to some virtual address
`va` can not bypass the older store tag initiated by `settag rs1=va`.

This specification defines tag as the entity associated to virtual addresses.
In case of aliasing (multiple virtual addresses map to same physical address),
it is software's responsibility to ensure that the tags are set according to
software's need for respective virtual address prior to memory accesses via
aliased virtual address.

===== Exceptions

`settag` can raise store page fault or access fault depending on how tag
storage is oragnized. If implementation doesn't support misaligned accesses,
`settag` instruction can raise misaligned exception if calculated address for
locating tag is unaligned. Tag storage memory must be idempotent memory else
`settag` raise store/AMO access-fault exception.

[[TAG_CHECKS]]
=== tag checks and privilege modes

If memory tagging is enabled for the execution environment, then memory tagging
checks are performed by extracting `pointer_tag` from the input pointer and
comparing `pointer_tag` against `mc_tag` associated with memory chunk for the
respective address. If the effective address range of a load/store spans
multiple memory chunks, the applicability of memory tag checks is determined
separately for each memory chunk.

==== M-mode
If memory tagging is enabled in M-mode (see <<MEM_TAG_EN>>), all regular loads
and regular stores are subject to memory tagging checks.

==== Less than M-mode
If memory tagging is enabled in the current execution environment (see
<<MEM_TAG_EN>>) and `satp.MODE == Bare`, then all regular loads and regular
stores are subject to tag checks.

If memory tagging is enabled in the current execution environment and
`satp.MODE != Bare`, then a regular load and regular store is subject to tag
checks only if the page is marked as a tagged page (see <<TAGGED_PAGE>>) in the
first stage page table.

==== tag checks
Once a regular load/store is determined (after paging bit checks and *envcfg
control bit checks) to be subject to memory tagging checks, following further
checks are performed

* All stack pointer (sp/x2) relative accesses are not checked for tags (see
  notes).

* Hart evaluates expression `mc_tag == pointer_tag` and if false then hart
  raises a software check exception with tval = 4.

While performing tag check on a regular load/store, fetching (load tag
operation) `mc_tag` from the tag memory region holding tags may also result in
a load page fault or load access fault and hart reports the virtual address of
the tag in `xtval`.

[NOTE]
=====
As much as possible, compiler uses stack pointer (x2) to access stack objects
local to a function. These accesses are deemed to be safe and thus are not
subject to tag checks.
=====

==== Explicit tag check
Zimt defines an explicit tag check instruction taken from `MOP.RR.1` of zimop
extension, `checktag rs1, #chunk_count`. If memory tagging is disabled in the
execution environment then `checktag` instruction reverts to zimop behavior. If
memory tagging is enabled in the execution environment then `checktag`
instruction extracts `pointer_tag` from `rs1` and performs load tag operation
for memory chunks (count = `#chunk_count`) starting at virtual address `rs1`.
If any of the loaded `mc_tag` value(s) mismatches with the `pointer_tag`
specified in `rs1`, then software check exception is raised with tval = 4. If
memory tagging is enabled in the execution environment then `checktag`
instruction always makes the check irrespective of `PTE.MTAG` bit setting for
the code page from where `checktag` instuction is fetched or for data page
virtual address specified in `rs1`.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['00000']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['tagged_pointer']},
  {bits:  4, name: 'tag_imm4', attr:['chunk_count']},
  {bits:  1, name: '0', attr:['0']},
  {bits:  7, name: '1000011', attr:['gentag']},
], config:{lanes: 1, hspace:1024}}
....

[[ASYNC_SW_CHECK]]
=== Asynchronous reporting for tag mismatches

To improve performance, software check exceptions due to tag mismatches on
regular stores can be reported asynchronously. This means that reported `epc`
might not be the reason for tag mismatch and software must do additional
analysis to infer which store resulted in software check exception. This
behavior can be optionally turned on through `__x__envcfg` CSR for next
less privilege mode (see <<MEMTAG_CSR_CTRL>>).

Note that tag check violations on regular loads must always be reported
synchronously.

[[TAGGED_PAGE]]
=== Tag checks on page basis

`Zimt` introduces `memory tag` (`MTAG`) bit in first stage page table which if
set in page table entry and memory tagging is enabled from *envcfg CSR,
following rules apply:

 1. tag checks are enforced on regular load/store to such page (tagged data
    page). See <<TAG_CHECKS>> for further checks. Underlying tagged page must
    be an idempotent memory else tag look up for referenced virtual memory will
    result in load access-fault exception.

 2. fetched instructions from a code page with `MTAG=1` (tag-exempt code page)
    generate unchecked load and store. This doesn't have any impact on behavior
    of `settag`, `gentag` and `addtag` instructions.

 3. If both rule 2 and rule 1 are applying, rule 2 takes precedence.

 4. An instruction crossing a page boundary with differing `MTAG` value, the
    instruction behaves as if it was fetched from a page with MTAG=0.

`MTAG` bit in page table entry remains a reserved bit if `XWR == 111` or
`XWR == 010` and if set, will raise a page fault of original access type.

If memory tagging is not enabled for the execution environment via *envcfg CSR,
then `MTAG` bit in page table entry remains a reserved and if set will raise a
page fault of original access type.

[NOTE]
====
`MTAG` bit on data pages allows software to opt into selected memory regions
to generate checked loads and stores. Furthermore, `MTAG` bit on executable
pages allows software to opt out certain code regions from being subject to
checked loads and stores. From usability point of view, shadow stack memory
accesses or self modifying code do not need `MTAG` bit. Thus `MTAG` bit is
kept as reserved for such page table encodings.
====

[[MEMTAG_CSR_CTRL]]
=== CSR bits for memory tagging

In M-mode, enable for memory tagging is controlled via `mseccfg` CSR.

Enablement for privilege modes less than M-mode is controlled through
`__x__envcfg` CSR. Zimt adds two bits termed as `MT_MODE` to `__x__envcfg`
CSR which controls enabling of memory tagging and `pointer_tag_width` for the
next privilege mode. A `MT_ASYNC` bit (bit 36) is added to `__x__envcfg` CSR
and if set, software check exceptions due to tag mismatches on store operations
can be reported asynchronously (see <<ASYNC_SW_CHECK>>).

[[MEM_TAG_EN]]
==== Memory tagging enable and pointer_tag_width

The term `xMT_MODE` is used to determine if memory tagging is enabled in
current execution environment (privilege mode).

Following table describes different encodings of `MT_MODE` and corresponding
configuration

.`MT_MODE` encoding and its meaning
[width=100%]
[%header, cols="^4,^12"]
|===
|`MT_MODE` | Memory tagging state
|  00       | Disabled
|  01       | Reserved
|  10       | Enabled, pointer_tag_width = 4
|  11       | Enabled, pointer_tag_width = 7
|===

  If memory tagging is implemented, implementation must implement
  `pointer_tag_width = 4` at minimum. To discover maximum supported
  `pointer_tag_width`, software can write `0b11` to `MT_MODE` field in the
  `__x__envcfg` CSR and read it back. If read back value is `0b11` then
  implementation supports both `pointer_tag` widths.

  If xMT_MODE == 0b00 then xenvcfg.MT_ASYNC becomes WPRI

==== Machine Security Configuration Register(`mseccfg`)

.Machine security configuration register(`mseccfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'MML'},
  {bits:  1, name: 'MMWP'},
  {bits:  1, name: 'RLB'},
  {bits:  5, name: 'WPRI'},
  {bits:  1, name: 'USEED'},
  {bits:  1, name: 'SSEED'},
  {bits:  1, name: 'MLPE'},
  {bits: 21, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MT_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits: 27, name: 'WPRI'},
], config:{lanes: 4, hspace:1024}}
....

The Zimt extension adds the `MT_MODE` field (bit 35:34) to `mseccfg`. When the
`MT_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
M-mode.

When `MT_MODE` is `0b00`, the following rules apply to M-mode:

* Zimt instructions will revert to their behavior as defined by Zimop.

==== Machine Environment Configuration Register (`menvcfg`)

.Machine environment configuration register (`menvcfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 24, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MT_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits: 23, name: 'WPRI'},
  {bits:  1, name: 'CDE'},
  {bits:  1, name: 'ADUE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

The Zimt extension adds the `MT_MODE` field (bit 35:34) to `menvcfg`. When the
`MT_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
HS/S-mode.

When `MT_MODE` is `0b00`, the following rules apply to HS/S-mode:

* Zimt instructions will revert to their behavior as defined by Zimop.

==== Supervisor Environment Configuration Register (`senvcfg`)

.Supervisor environment configuration register (`senvcfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 24, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MT_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits: 27, name: 'WPRI'},
], config:{lanes: 4, hspace:1024}}
....

The Zimt extension adds the `MT_MODE` field (bit 35:34) to `senvcfg`. When the
`MT_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
VU/U-mode.

When `MT_MODE` is `0b00`, the following rules apply to VU/U-mode:

* Zimt instructions will revert to their behavior as defined by Zimop.

==== Hypervisor Environment Configuration Register (`henvcfg`)

.Hypervisor environment configuration register (`henvcfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 24, name: 'WPRI'},
  {bits:  2, name: 'PMM'},
  {bits:  2, name: 'MT_MODE'},
  {bits:  1, name: 'MT_ASYNC'},
  {bits: 23, name: 'WPRI'},
  {bits:  1, name: 'CDE'},
  {bits:  1, name: 'ADUE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

The Zimt extension adds the `MT_MODE` field (bit 35:34) to `henvcfg`. When the
`MT_MODE` field is set to `0b10` or `0b11`, memory tagging is enabled for
VS-mode.

When `MT_MODE` is `0b00`, the following rules apply to VS-mode:

* Zimt instructions will revert to their behavior as defined by Zimop.

<<<

=== Appendix
==== Example: stack tagging codegen
[listing]
-----
    function:
        # N.B. sp remains untagged at all times
        addi sp, sp, -512 # stack frame size of 512 bytes
        gentag t0, zero   # generate a pointer_tag in high bits of t0
         :
        # first object is tagged <random tag> + 1
        addi s1, sp, 16
        addtag t1, t0, 1  # tag_imm4 = 1
        or s1, s1, t1
         :
        # second object is tagged <random tag> + 2
        addi s2, sp, 32
        addtag t1, t0, 2  # tag_imm4 = 2
        or s2, s2, t1
         :
        # scope of second object starts, tag
        settag s2, 1
        # [...] do things with s2 while in scope
        # scope of second object ends, tag back to zero
        addi s2, sp, 16
        settag s2, 1
-----
